# Generated by Django 5.1.3 on 2024-11-20 12:41

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Peraturan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jenis_peraturan', models.CharField(max_length=255)),
                ('judul_peraturan', models.TextField()),
                ('tahun_terbit', models.PositiveIntegerField()),
                ('nomor', models.CharField(max_length=50)),
                ('singkatan_jenis', models.CharField(max_length=50)),
                ('tanggal_penetapan', models.DateField()),
                ('tanggal_pengundangan', models.DateField()),
                ('teu_badan', models.CharField(max_length=255)),
                ('sumber', models.CharField(max_length=255)),
                ('tempat_terbit', models.CharField(max_length=255)),
                ('bidang_hukum', models.CharField(max_length=255)),
                ('subjek', models.CharField(max_length=255)),
                ('bahasa', models.CharField(max_length=50)),
                ('lokasi', models.CharField(max_length=255)),
                ('urusan_pemerintahan', models.CharField(max_length=255)),
                ('status_produk', models.CharField(max_length=50)),
                ('keterangan_status', models.TextField()),
                ('penandatangan', models.CharField(max_length=255)),
                ('pemrakarsa', models.CharField(max_length=255)),
                ('peraturan_terkait', models.TextField()),
                ('dokumen_terkait', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='PeraturanVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version_number', models.PositiveIntegerField()),
                ('is_final', models.BooleanField(default=False)),
                ('pdf_file', models.FileField(upload_to='peraturan_pdfs/')),
                ('extracted_content', models.JSONField()),
                ('changed_fields', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('peraturan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='peraturan.peraturan')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['version_number'],
                'unique_together': {('peraturan', 'version_number')},
            },
        ),
    ]
