# Generated by Django 5.1.3 on 2024-11-20 12:59

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('peraturan', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='peraturan',
            name='peraturan_terkait',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=255), blank=True, null=True, size=None),
        ),
    ]
