# Generated by Django 5.1.3 on 2024-12-02 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('peraturan', '0002_alter_peraturan_peraturan_terkait'),
    ]

    operations = [
        migrations.AlterField(
            model_name='peraturan',
            name='bahasa',
            field=models.CharField(choices=[('id', 'Indonesian'), ('en', 'English')], max_length=50),
        ),
        migrations.AlterField(
            model_name='peraturan',
            name='jenis_peraturan',
            field=models.CharField(choices=[('UU', 'Undang-Undang'), ('PP', 'Peraturan Pemerintah'), ('Perpres', 'Peraturan Presiden')], max_length=255),
        ),
        migrations.AlterField(
            model_name='peraturan',
            name='status_produk',
            field=models.CharField(choices=[('draft', 'Draft'), ('final', 'Final'), ('revised', 'Revised')], max_length=50),
        ),
    ]
