# Generated by Django 5.1.3 on 2024-12-02 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('peraturan', '0003_alter_peraturan_bahasa_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='peraturan',
            name='id_tracking',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
